# Generated by Django 3.2.5 on 2021-07-31 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pollspartyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='none', max_length=255)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 7, 31, 17, 13, 37, 800217, tzinfo=utc))),
                ('poll', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token', to='pollspartyapp.poll')),
            ],
        ),
    ]
