# Generated by Django 3.2.5 on 2021-07-31 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pollspartyapp', '0002_polltoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polltoken',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 17, 22, 37, 407498, tzinfo=utc)),
        ),
    ]
