# Generated by Django 3.2.5 on 2021-07-31 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pollspartyapp', '0003_alter_polltoken_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polltoken',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
