# Generated by Django 3.2.5 on 2021-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollspartyapp', '0004_alter_polltoken_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expires_in',
            field=models.IntegerField(null=True),
        ),
    ]
